# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Data Science - Przegląd Zagadnień"
author: "Dudycz H., Zygała R., Wójcik F.. Redakcja i opracowanie techniczne: Wójcik F."
copyright: "Dudycz H., Zygała R., Wójcik F., 2024"
logo: ./images/logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  stderr_output: 'error'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  extra_footer: |
    Cytowanie: <a href="https://doi.org/10.5281/zenodo.13369871"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.13369871.svg" alt="DOI"></a> <br>
    Logo: image by <a href="https://pixabay.com/users/mcmurryjulie-2375405/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=2031395">mcmurryjulie</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=2031395">Pixabay</a>

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    language: "pl"
  extra_extensions:
    - sphinx_proof

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"


repository:
  url: https://github.com/maddataanalyst/ds_book
  path_to_book: ds_ue_script
  branch: main
